languageCode = "en-us"
title = "Carina"
baseURL = "https://xjy2061.github.io/carina/"
theme = "bootstrap"

[author]
  name = "xjy2061"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Captain log"
  Author = "xjy2061"
  email = "xjy2061@gmail.com" #Remove this line if you would prefer not to use an email button in the footer.
  #postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  #showReadTime = true #set to false to exclude read time from header of post

[[params.social]]
  title = "github"
  url = "https://github.com/xjy2061"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Notes"
  url = "/note/"
  weight = -180