title = "Carina"
baseURL = "https://xjy2061.github.io/carina/"
languageCode = "en-us"
theme = "ananke"

[author]
  name = "xjy2061"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Notes"
  url = "/note/"
  weight = -180